apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: victim-service
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - app
  selector:
    matchLabels:
      app: victim-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
